repos:
  # general hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json

  # python hooks
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.19.1"
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
      # Run the linter.
      - id: ruff
        args: [--fix] # --output-format=github
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.15.0"
    hooks:
      - id: mypy
        args: ["--config", "pyproject.toml"]

  # cpp hooks
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: "v1.3.5"
    hooks:
      - id: clang-format
        args: [--style=Google]
      - id: clang-tidy
      - id: include-what-you-use
