[tool.ruff]
line-length = 120

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
extend-select = [
  "E",   # Pydocstyle-errors
  "W",   # Pydocstyle-warnings
  "F",   # Pyflakes
  "PL",  # Pylint
  "I",   # isort
  "C90", # mccabe
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "D",   # pydocstyle
  "B",   # flake8-bugbear
  "A",   # flake8-builtins
  "PT",  # flake8-pytest-style
  "Q",   # flake8-quotes
  "RUF", # Ruff-specific rules
  "COM", # flake8-commas
]

ignore = [
    "COM812", "ISC001",     # "Trailing comma missing"
    "D100",                 # Docstrings in public module
    "D107",                 # Missing docstring in `__init__`
    "N812",                 # Lowercase `functional` imported as non-lowercase `F
    "T201",                 # `print` found
    "PLR0913",              # Too many arguments in function definition
    "FBT003",               # Boolean positional value in function call
    "S101",                 # Use of `assert` detected
    "FA102",                # from __future__ import annotations missing for compatibility
    "RET504",               # Unnecessary assignment to `inputs` before `return` statement
    "D202",                 # No blank lines allowed after function docstring
    "ERA001",               # Found commented-out code
    "D104",                 # Missing docstring in public package
    "EM102"                 # Exception must not use an f-string literal, assign to variable first
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
ignore_missing_imports = true
# strict = true     # TODO: eventually add back proper type checks

[tool.pytest.ini_options]
python_files = ["test_*.py"]
