[tool.black]
line_length = 120


[tool.isort]
profile = "black"
line_length = 120

[tool.pydocstyle]
convention = "google"


[tool.pylint]
fail-under = 9
max-line-length = 120


[tool.mypy]


[tool.pytest.ini_options]
python_files = ["test_*.py"]
