[tool.ruff]
line-length = 120

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
extend-select = [
  "E",   # Pydocstyle-errors
  "W",   # Pydocstyle-warnings
  "F",   # Pyflakes
  "PL",  # Pylint
  "I",   # isort
  "C90", # mccabe
  "UP",  # pyupgrade
  "N",   # pep8-naming
  "D",   # pydocstyle
  "B",   # flake8-bugbear
  "A",   # flake8-builtins
  "PT",  # flake8-pytest-style
  "Q",   # flake8-quotes
  "RUF", # Ruff-specific rules
  "COM", # flake8-commas
]

ignore = [
    "COM812", "ISC001"  # "Trailing comma missing"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
ignore_missing_imports = true
# strict = true     # TODO: eventually add back proper type checks

[tool.pytest.ini_options]
python_files = ["test_*.py"]
