[tool.pylint.main]
fail-under = 8

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = ["import-error"]

[tool.black]
line_length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pydocstyle]
convention = "google"
add_ignore = ["D100", "D104", "D107", "D202", "D101", "D102", "D103"] # TODO: eventually add back "D101", "D102", "D103"

[tool.mypy]
ignore_missing_imports = true
strict = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
