name: env_industrial_det
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - transformers
  - opencv
  - scipy
  - numpy
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu126
      - torchvision  --index-url https://download.pytorch.org/whl/cu126
      - torchaudio  --index-url https://download.pytorch.org/whl/cu126
      - onnx
      - onnxruntime-gpu
      - onnxconverter_common
      - open3d
