dataset:
  name: "ImageFolder_overfit"
  directory: "~/workspace/diffusion/data/ImageFolder_overfit/"
  shuffle: True
  num_workers: 0
  pin_memory: False

diffusion:
  num_steps: 1000
  noise_schedule: "cosine"

model:
  class_cond: True
  unet_hidden_dims: [32, 64, 128, 256]
  ema_decay: 0.999

experiment:
  data_shape: [3, 32, 32]
  num_epochs: 26
  batch_size: 64
  optim_lr: 0.0002
  lr_schedule_mult: 0.1 # 1.0 effectively ignores schedule
  device: "cuda"
  dtype: "float32" # NOTE: bfloat16 is possible and faster on Ampere+ GPUs, but results are not stable for some reason
  eval_interval: 5
  eval_dir: ./ImageFolder_overfit/reverse_diffusion
  checkpoints_dir: ./ImageFolder_overfit/checkpoints
