dataset:
  name: "MNIST"
  directory: "~/workspace/diffusion/data/"
  shuffle: True
  num_workers: 0
  pin_memory: False

diffusion:
  num_steps: 1000
  noise_schedule: "linear"
  beta_1: 1e-4
  beta_T: 0.02

model:
  name: "UNet2d"
  hidden_dims: [32, 64, 128, 256]
  class_cond: True
  ema_decay: 0.999
  dropout: 0.05

experiment:
  data_type: "img"
  data_shape: [1, 28, 28]
  num_epochs: 31
  batch_size: 64
  optim_lr: 0.0005
  lr_schedule_mult: 0.1 # 1.0 effectively ignores schedule
  device: "cuda"
  dtype: "float32"
  eval_interval: 5
  eval_num: 100
  eval_dir: ./MNIST/reverse_diffusion
  checkpoints_dir: ./MNIST/checkpoints
  checkpoint_path: ""
