dataset:
  name: "ModelNet10"
  directory: "~/workspace/diffusion/data/"
  shuffle: True
  num_workers: 0
  pin_memory: False

diffusion:
  num_steps: 500
  noise_schedule: "linear"
  beta_1: 1e-6
  beta_T: 5e-4

model:
  # name: "PointDiffusionTransformer" quite heavy for smaller gpus :(
  # hidden_dims: [64, 64, 64, 64, 64]
  # context_dim: 32
  name: "PointNet" # PointNet
  hidden_dims: [128, 256, 512, 256, 128]
  context_dim: 128
  class_cond: True
  ema_decay: 0.999
  dropout: 0.0

experiment:
  data_type: "pcd"
  data_shape: [3, 3000]
  num_epochs: 101
  batch_size: 64
  optim_lr: 0.0005
  lr_schedule_mult: 0.1 # 1.0 effectively ignores schedule
  device: "cuda"
  dtype: "float32"
  eval_interval: 10
  eval_num: 100
  eval_dir: ./ModelNet10/reverse_diffusion
  checkpoints_dir: ./ModelNet10/checkpoints
  checkpoint_path: ""
