name: Gatekeeper checks

on:
  pull_request:
    branches: [main]

  # add option to launch manually
  workflow_dispatch:

# jobs to run:
jobs:
  SCA-python:
    # FIXME: only run job if not draft PR and gatekeeper tag was added
    #if: github.event.pull_request.draft == false && startsWith(github.ref, 'refs/tags/gatekeeper')

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (${{ matrix.python-version }})
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SCA Python tools
        run: |
          pip install \
              black \
              isort \
              pydocstyle \
              flake8 \
              mypy \
              pylint

      - name: "Check SCA: black"
        run: python -m black "./" --check --config="pyproject.toml"

      - name: "Check SCA: isort"
        run: python -m isort "./" --check-only --settings-path="pyproject.toml"

      - name: "Check SCA: flake8"
        run: python -m flake8 "./" --count --config="setup.cfg"

      - name: "Check SCA: pylint"
        run: python -m pylint "./" --recursive "y" --rcfile="pyproject.toml"

      - name: "Check SCA: mypy"
        run: python -m mypy "./" --config="pyproject.toml"

      - name: "Check SCA: pydocstyle"
        run: python -m pydocstyle "./" --count --config="pyproject.toml"
